@"
stages:
  process:
    cmd: python src/data_loader.py
    deps:
      - data/MachineLearningRating_v3.txt
      - src/data_loader.py
    outs:
      - data/processed_data.csv
"@ | Out-File -FilePath "dvc.yaml" -Encoding utf8